In [1]:
import pandas as pd
import numpy as np
import scipy.stats as s
import os
import matplotlib.pyplot as plt

In [2]:
basepath="./DevanagariHandwrittenCharacterDataset/Train"
list_of_folders=os.listdir(basepath)
list_of_folders

['character_10_yna',
 'character_11_taamatar',
 'character_12_thaa',
 'character_13_daa',
 'character_14_dhaa',
 'character_15_adna',
 'character_16_tabala',
 'character_17_tha',
 'character_18_da',
 'character_19_dha',
 'character_1_ka',
 'character_20_na',
 'character_21_pa',
 'character_22_pha',
 'character_23_ba',
 'character_24_bha',
 'character_25_ma',
 'character_26_yaw',
 'character_27_ra',
 'character_28_la',
 'character_29_waw',
 'character_2_kha',
 'character_30_motosaw',
 'character_31_petchiryakha',
 'character_32_patalosaw',
 'character_33_ha',
 'character_34_chhya',
 'character_35_tra',
 'character_36_gya',
 'character_3_ga',
 'character_4_gha',
 'character_5_kna',
 'character_6_cha',
 'character_7_chha',
 'character_8_ja',
 'character_9_jha',
 'digit_0',
 'digit_1',
 'digit_2',
 'digit_3',
 'digit_4',
 'digit_5',
 'digit_6',
 'digit_7',
 'digit_8',
 'digit_9']

In [3]:
def images_convert_pixel(each_image_path):
    image_pixel=plt.imread(each_image_path)
    image_pixel=image_pixel.reshape(1,1024)
    return image_pixel

In [4]:
stack_images=[]
for one_folder in list_of_folders:
    folder_path=os.path.join(basepath,one_folder)
    list_of_images=os.listdir(folder_path)
    stack_images.extend(map(lambda x:images_convert_pixel(os.path.join(folder_path,x)),list_of_images))

In [5]:
len(stack_images)

78200

In [6]:
stack_images=np.array(stack_images)
stack_images.shape

(78200, 1, 1024)

In [7]:
stack_images=stack_images.reshape(78200,1024)
stack_images.shape

(78200, 1024)

In [8]:
training_data=pd.DataFrame(stack_images)
training_data

0     1     2     3     4     5     6     7     8     9     ...  1014  \
0       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
78195   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
78196   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
78197   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
78198   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
78199   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

       1015  1016  1017  1018  1019  1020  1021  1022  1023  
0       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
78195   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
78196   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
78197   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
78198   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
78199   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[78200 rows x 1024 columns]

In [9]:
len(list_of_folders)

46

In [10]:
78200/len(list_of_folders)

1700.0

In [11]:
labels=[]
labels.extend(map(lambda x: x*np.ones((1700,1)),np.arange(0,46)))

In [12]:
labels=np.concatenate(labels)

In [13]:
labels

array([[ 0.],
       [ 0.],
       [ 0.],
       ...,
       [45.],
       [45.],
       [45.]])

In [14]:
labels.shape

(78200, 1)

In [15]:
training_data['labels'] = labels

In [16]:
training_data

0    1    2    3    4    5    6    7    8    9  ...  1015  1016  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
78195  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
78196  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
78197  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
78198  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
78199  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

       1017  1018  1019  1020  1021  1022  1023  labels  
0       0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
1       0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
2       0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
3       0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
4       0.0   0.0   0.0   0.0   0.0   0.0   0.0     0.0  
...     ...   ...   ...   ...   ...   ...   ...     ...  
78195   0.0   0.0   0.0   0.0   0.0   0.0   0.0    45.0  
78196   0.0   0.0   0.0   0.0   0.0   0.0   0.0    45.0  
78197   0.0   0.0   0.0   0.0   0.0   0.0   0.0    45.0  
78198   0.0   0.0   0.0   0.0   0.0   0.0   0.0    45.0  
78199   0.0   0.0   0.0   0.0   0.0   0.0   0.0    45.0  

[78200 rows x 1025 columns]

In [17]:
label = np.array(training_data['labels'])

y=label

In [18]:
labels = label.reshape(labels.shape[0],1)

In [19]:
labels.shape

(78200, 1)

In [20]:
labels = np.uint8(labels)

In [21]:
labels

array([[ 0],
       [ 0],
       [ 0],
       ...,
       [45],
       [45],
       [45]], dtype=uint8)

In [22]:
X = training_data.drop(['labels'],axis=1)
X=np.array(X)

## USING SKLEARN WITHOUT PCA ##

In [57]:
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [24]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size= 0.2, random_state = 1)

print('X_train dimension= ', X_train.shape)
print('X_test dimension= ', X_test.shape)
print('y_train dimension= ', y_train.shape)
print('y_test dimension= ', y_test.shape)


X_train dimension=  (62560, 1024)
X_test dimension=  (15640, 1024)
y_train dimension=  (62560,)
y_test dimension=  (15640,)


In [25]:
lm = linear_model.LogisticRegression(multi_class='multinomial', solver='lbfgs')
lm.fit(X_train, y_train)

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [26]:
print('Predicted value is =', lm.predict([X_test[200]]))

print('Actual value from test data is %s and corresponding test is %',(y_test[200]) )

Predicted value is = [6.]
Actual value from test data is %s and corresponding test is % 6.0


In [27]:
lm.score(X_test, y_test)

0.7277493606138108

## USING SKLEARN WITH PCA ##

In [28]:
sigma = np.cov(X,rowvar=False)

In [29]:
def pca_reduced_data(whole_data_single_cov_mat,preserved_variance):
    
    svd_factorized_matrix = np.linalg.svd(whole_data_single_cov_mat)
    
    eig_vals_total = np.sum(svd_factorized_matrix[1])
    
    eig_vals_sum = 0
    
    i = 0
    
    for lmda in svd_factorized_matrix[1]:
        
        if eig_vals_sum/eig_vals_total > preserved_variance:
            
            break
        
        i+=1
        
        eig_vals_sum += lmda
        
    eig_vecs = svd_factorized_matrix[0][:,0:i]
    
    training_examples = X
    
    reduced_training_examples = np.matmul(training_examples,eig_vecs)
    
    return reduced_training_examples,eig_vecs

In [30]:
X_PCA,eigen_vectors=pca_reduced_data(sigma,0.95)

In [31]:
X_train_PCA, X_test_PCA, y_train, y_test = model_selection.train_test_split(X_PCA, y, test_size= 0.2, random_state = 1)

print('X_train_PCA dimension= ', X_train_PCA.shape)
print('X_test_PCA dimension= ', X_test_PCA.shape)
print('y_train dimension= ', y_train.shape)
print('y_test dimension= ', y_test.shape)

X_train_PCA dimension=  (62560, 174)
X_test_PCA dimension=  (15640, 174)
y_train dimension=  (62560,)
y_test dimension=  (15640,)


In [65]:
lm_PCA = linear_model.LogisticRegression(multi_class='multinomial', solver='lbfgs',max_iter=12000)
lm_PCA.fit(X_train_PCA, y_train)

LogisticRegression(max_iter=12000, multi_class='multinomial')

In [66]:
lm_PCA.score(X_test_PCA, y_test)

0.7349744245524297

## FROM SCRATCH ##

In [36]:
I = np.eye(46,46)

In [37]:
print(I)
I.shape

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


(46, 46)

In [38]:
O = I[labels]
O.shape

(78200, 1, 46)

In [39]:
O = O.reshape(78200,46)

In [40]:
O.shape

(78200, 46)

In [41]:
O

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [42]:
normalized_data,eig_vecs_final = pca_reduced_data(sigma,0.95)

In [43]:
normalized_data.shape

(78200, 174)

In [44]:
M = O.shape[1]
print("M",M)
N_train = O.shape[0]
print("N_train",N_train)
N = normalized_data.shape[1]
print("N",N)

M 46
N_train 78200
N 174


In [45]:
def P(theta0,theta,normalized_data):
    
    U = np.exp(theta0 + np.matmul(normalized_data,theta))
    
    S = np.sum(U,axis=1).reshape(78200,1)
    
    return U/S

In [46]:
def neg_log_loss(O,P):
    
    O_logP = np.log(P) * O
    
    return -np.mean(np.sum(O_logP,axis=1))

In [47]:
def derivatives(normalized_data,P,O):
    
    del_theta0 = (1/N_train) * np.sum((O-P),axis=0)
    
    del_theta = (1/N_train) * np.matmul(normalized_data.T,(O-P))
    
    return del_theta0,del_theta

In [48]:
tol = 10**(-6)

step_size = 1.1

theta0_initial = np.random.randn(1,M)

theta_initial = np.random.randn(N,M)

iterations = []

neg_log_loss_history = []

i = 0

while(True):
    
    P_initial = P(theta0_initial,theta_initial,normalized_data)
    
    del_theta0_initial, del_theta_initial = derivatives(normalized_data,P_initial,O)
    
    
    
    theta0_final = theta0_initial + step_size *(del_theta0_initial)
    
    theta_final = theta_initial + step_size *(del_theta_initial)
    
    
    P_final = P(theta0_final,theta_final,normalized_data)
    
    
    
    neg_log_loss_initial = neg_log_loss(O,P_initial)
    
    neg_log_loss_final = neg_log_loss(O,P_final)
    
    
    
    if abs(neg_log_loss_final - neg_log_loss_initial) < tol:
        
        break
        
    
    theta0_initial = theta0_final
    
    theta_initial = theta_final
    
    
    iterations.append(i)
    
    neg_log_loss_history.append(neg_log_loss_initial)
    
    print("iteration # =",i,"and neg log loss =",neg_log_loss_initial)
    
    i += 1

iteration # = 0 and neg log loss = 31.757726650779805
iteration # = 1 and neg log loss = 26.160090530764812
iteration # = 2 and neg log loss = 23.75817367348274
iteration # = 3 and neg log loss = 22.26717904638029
iteration # = 4 and neg log loss = 21.12118593156594
iteration # = 5 and neg log loss = 20.16568541767428
iteration # = 6 and neg log loss = 19.348789636434315
iteration # = 7 and neg log loss = 18.640510848951926
iteration # = 8 and neg log loss = 18.012047976763686
iteration # = 9 and neg log loss = 17.437421744047562
iteration # = 10 and neg log loss = 16.902153894078126
iteration # = 11 and neg log loss = 16.400729847395063
iteration # = 12 and neg log loss = 15.929863723924504
iteration # = 13 and neg log loss = 15.485280302270326
iteration # = 14 and neg log loss = 15.0626222379475
iteration # = 15 and neg log loss = 14.659107094184296
iteration # = 16 and neg log loss = 14.273296031472922
iteration # = 17 and neg log loss = 13.904396085593078
iteration # = 18 and neg l

In [49]:
P_trained = P(theta0_final,theta_final,normalized_data)

In [50]:
P_trained.shape

(78200, 46)

In [51]:
predicted_classes_train = np.argmax(P_trained,axis=1)

In [52]:
predicted_classes_train = predicted_classes_train.reshape(predicted_classes_train.shape[0],1)

In [53]:
actual_classes_train = np.argmax(O,axis=1)

In [54]:
actual_classes_train = actual_classes_train.reshape(actual_classes_train.shape[0],1)

In [60]:
correct_count = np.count_nonzero(np.equal(predicted_classes_train,actual_classes_train))
correct_count

59548

In [64]:
correct_count_percentage=(np.count_nonzero(np.equal(predicted_classes_train,actual_classes_train)))/actual_classes_train.shape[0]
correct_count_percentage

0.7614833759590793